### ISSUE TITLE
Return an exit code for RunTargetsWithoutExiting 

### ISSUE THREAD

**Issue by damianh** [adamralph/bullseye#418] opened 2020-05-20 14:51 UTC
## Use case(s)

I want to be able to run some (cleanup) code after running the targets regardless of success/failure and still exit with the appropriate exit code 

## Description

Example: 

```
var exitCode = RunTargetsWithoutExiting(args);
StopContainers();
return exitCode; // or Environment.Exit(exitCode);
```

## Alternatives

I have none.

## Additional context

NA

**Comment by adamralph** [comment] 2020-05-20 17:07
Hey @damianh, thanks for raising this.

If you are using `RunTargetsWithoutExiting`, you can use a regular `finally`:

```c#
try
{
    RunTargetsWithoutExiting(args);
}
finally
{
    StopContainers();
}
```

There are essentially two method groups: `RunTargetsWithoutExiting` and `RunTargetsAndExit`.  

`RunTargetsWithoutExiting` is "normal". It allows exceptions to pass up the stack, similar to most .NET methods. From the API perspective, it's all that's required. Older versions of Bullseye contained only this method group, and it was named simply `RunTargets`.

The problem is that Bullseye's canonical usage is in a build "script" in a console app, and [allowing the runtime to handle exceptions is ugly](https://github.com/adamralph/bullseye/issues/172). For that reason, we introduced `RunTargetsAndExit`, and renamed `RunTargets` to `RunTargetsWithoutExiting` to distinguish the behaviours.

`RunTargetsAndExit` is "special". It terminates the process with an appropriate exit code, catching and logging exceptions. It exists to save you writing something like this every time — https://github.com/adamralph/bullseye/blob/aa05c2b1adcd0a6a76579299bb21e85a15acc395/Bullseye/Internal/TargetCollectionExtensions.cs#L45-L55

Ultimately, your build "script" is _your_ console app, including any mapping from exceptions to exit codes. `RunTargetsAndExit` provides you with a pre-built opinion for the simple case.

I guess we could introduce a _new_ method group to return the exit code instead of terminating the process, something like `RunTargetsAndGetExitCode`, but it would only provide a minor variant of the above code, and you could do that yourself. I'm also hesitant to introduce an error-based method group in a .NET API, which is expected to be exception-based. `RunTargetsAndExit` is arguably already an API crime, but its convenience was just too compelling.

I guess another possibility is to extend `RunTargetsAndExit` to also cover the more complex case of a `finally` block with a new optional parameter:

```c#
RunTargetsAndExit(args, finally: () => StopContainer());
```

I guess the danger is that someone will then ask to be able to handle the exceptions in a custom way, and we'll end up with an optional parameter for each `catch` block. 🙂

**Comment by damianh** [comment] 2020-05-22 11:46
Awesome detailed response as always lad :)

Try catch will work and I considered that, but I have a bit of an aversion to exception based control of flow. But.. it's a build program, so it doesn't rustle my jimms too much.

Another reason I created the isssue is that there is an asymmetry between `RunTargetsWithoutExiting` being exception based and `RunTargetsAndExit` being exit code based.

> then ask to be able to handle the exceptions in a custom way

I can totally see that happening.

I'll proceed with try-catch with custom exit code.

**Comment by adamralph** [comment] 2020-05-22 12:56
> I have a bit of an aversion to exception based control of flow

Me too generally, but in a console app where you want to control the exit code and/or avoid passing the exception to the runtime, you will always have to do this. I'd also argue that, in the outer-most stack of the program, it's OK. It's the translation/integration point between a .NET API and the terminal, so it seems like a valid thing to be doing.

> there is an asymmetry between `RunTargetsWithoutExiting` being exception based and `RunTargetsAndExit` being exit code based

`RunTargetsAndExit` isn't really exit/error code based, since it's a `void` method. It also doesn't catch the general `Exception` type. It only catches two "expected" exceptions which are thrown when either bad CLI args are passed or targets have failed, either due to a bug in user code or some external resource failure. Given that other exceptions _will_ pass up the stack, it's arguable that `RunTargetsAndExit` is still exception based, and it's just peforming desired action in the case of an external fault. I guess that could be another argument that "exception based control of flow" is OK here.

In any case, `RunTargetsAndExit` is a "weird" method. It's a kind of "opinionated wrapper" around `Environment.Exit`. I guess a purist would always use `RunTargetsWithoutExiting`. 🙂

Closing this as a `wontfix` for now, but that doesn't mean I'll never listen to arguments for it again.

**Closed by adamralph** 2020-05-22 12:56 UTC
Labels: enhancement, wontfix

**Comment by damianh** [comment] 2020-05-26 08:30
Reasonable, and thanks for the discussion 😉

**Comment by damianh** [comment] 2020-06-05 08:31
So this is what I have now to replicate the RunTargetsAndExit but with a custom `finally` and to have the same experience. The thing that I don't like about this is the `await ConsoleExtensions.Initialize` in order to get a log so the error experience for InvalidUsageException is the same. Any suggestions on improving this?

```
try
{
    await RunTargetsWithoutExitingAsync(args);
}
catch (InvalidUsageException ex)
{
    var (_, log) = await ConsoleExtensions.Initialize(new Options(), "BullsEye");
    await log.Error(ex.Message).Tax();
    Environment.Exit(2);
}
catch (TargetFailedException)
{
    Environment.Exit(1);
}
finally
{
    StopContainers();
}
```

**Comment by damianh** [comment] 2020-06-05 08:54
Side note: would like access to the `log` instead of Console.Writeline, so I presume I just need to create my own one anyway?

**Comment by adamralph** [comment] 2020-06-05 10:17
You shouldn't be using `ConsoleExtensions.Initialize()` or `Logger`. They are in the internal namespace. As a side note, I sometimes regret that taking strategy and not actually making everything in their `internal`. 🙄

I would just do:

```c#
await Console.Error.WriteLineAsync(ex.Message);
```

BTW I'm not sure whether `Tax()` is the one from Bullseye (which, again, you shouldn't be using) or your own, but I don't think you need it, since this code lives in your console app and not a lib.

> Note: an `Environment.Exit` inside a `catch` means the `finally` doesn't run.

👍 that's what I would expect.

**Comment by adamralph** [comment] 2020-06-05 10:22
BTW I can see why this might start to feel a bit messy, so now I find myself considering this again:

> I guess another possibility is to extend `RunTargetsAndExit` to also cover the more complex case of a `finally` block with a new optional parameter:
> 
> ```c#
> RunTargetsAndExit(args, finally: () => StopContainer());
> ```

**Comment by damianh** [comment] 2020-06-05 10:53
`Tax()` made me lol. It was just copy pasta.

`
await Console.Error.WriteLineAsync(ex.Message);
`
works but is just not pretty like the log output.

**Comment by adamralph** [comment] 2020-06-06 09:58
@damianh before embarking on a new feature, I'd like to explore the use case a little.

I assume that some target is setting something up that needs to be torn down regardless of success/failure. In this specific case, spinning up some containers, which need to be stopped. Note that close to _everything_ should be done inside targets, rather than in "loose" code outside targets. The latter doesn't really fit the Bullseye model, since for example, you'd be spinning up containers when running `--help`, `--list-targets`, `--dry-run`, etc.

Are my assumptions correct?

If so, there is another possibility. We could introduce a way of specifying a tear down action for each target. That way, you would only tear down containers if the target that spun them up had run. We could even go more specific and register objects for disposal within targets. This has the benefit of the target and the tear down not having to cooperate on what succeeded and requires tearing down, and what failed and doesn't require tearing down. E.g.

```c#
Target("start-containers", () =>
{
    this.container1 = Container.Start(...).Using();
    this.container2 = Container.Start(...).Using();
});
```

The `Using()` extension method would register the object for disposal after the target exits, regardless of success/failure, just like a `using` block. FWIW, xBehave.net already has the [equivalent feature](https://github.com/xbehave/xbehave.net/wiki/Object-disposal).

**Comment by adamralph** [comment] 2020-06-07 12:02
After more thought, `.Using()` wouldn't work because of the `--parallel` option. Bullseye would have to pass a context object `c` to the target action which would have to be passed to `.Using(c)` to associate the disposal with the target, just as in xBehave.net. And that would clash with the `Target()` overloads with `forEach` where the action already accepts an input parameter.

So the other option left on the table is a cooperative tear down for each target. Something like:

```c#
Target(
    "start-containers",
    () => StartContainers(),
    () => StopContainersIfStarted());
```

Of course, there are various ways of building your internal DSL. E.g. you could choose to wrap the lifetime of the containers in a disposable object and in the tear down just conditionally dispose:

```c#

Containers containers;

Target(
    "start-containers",
    () => containers = StartContainers(),
    () => containers?.Dispose());
```

**Comment by damianh** [comment] 2020-06-09 11:17
> Note that close to _everything_ should be done inside targets, rather than in "loose" code outside targets. The latter doesn't really fit the Bullseye model, since for example, you'd be spinning up containers when running `--help`, `--list-targets`, `--dry-run`, etc.
> 
> Are my assumptions correct?

This is correct.

> If so, there is another possibility. We could introduce a way of specifying a tear down action for each target. 

Smells somewhat similar to this https://github.com/adamralph/bullseye/issues/218 . I prefer the "option left on thre table".

In conjunction with optional tearup / teardown for each target, would a global tearup / teardown for the script as a whole makes sense or provide value? In the sense it's a place where the "lose" code goes. Maybe not initially for this feature, but perhaps worth considering in case this feature would affect design of such a thing.

**Comment by adamralph** [comment] 2020-07-05 16:42
> would a global tearup / teardown for the script as a whole makes sense or provide value? In the sense it's a place where the "lose" code goes

I can't think of a use case right now, but we could introduce it later if required.

BTW, the target itself is effectively the "tearup", unless I'm missing something?

**Comment by adamralph** [comment] 2020-07-05 17:06
@damianh I've raised #440 to capture the new proposal.
