### ISSUE TITLE
Not able to use inside Worker template 

### ISSUE THREAD

**Issue by iAmBipinPaul** [adamralph/bullseye#435] opened 2020-06-28 18:59 UTC
### 1. When running with `RunTargetsAndExit `
```csharp
 protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                Target("default", () => System.Console.WriteLine("Hello, world!"));
                RunTargetsAndExit(decimal);
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
```
 It runs first time but stops the application and gets stuck on 
```
Waiting for the host to be disposed. Ensure all 'IHost' instances are wrapped in 'using' blocks.
```
![image](https://user-images.githubusercontent.com/9201481/85955703-35fe8500-b9a0-11ea-8c12-6810a130036d.png)

### 2. When running with `RunTargetsWithoutExiting` 

```csharp
 protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                Target("default", () => System.Console.WriteLine("Hello, world!"));
                RunTargetsWithoutExiting(default);
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
```

It runs first time but  gets stuck on  

![image](https://user-images.githubusercontent.com/9201481/85955779-d6ed4000-b9a0-11ea-9c74-50fd7ded4c7e.png)

**Comment by adamralph** [comment] 2020-06-29 05:27
Hi @iAmBipinPaul, thanks for raising this.

I'm not familiar with the "Worker template". Can you share a full example with me?

BTW, `RunTargetsWithoutExiting` is probably what you want, because by calling `RunTargetsAndExit`, you are effectively handing over the remaining lifetime of your application to Bullseye.

**Comment by iAmBipinPaul** [comment] 2020-06-29 05:46
@adamralph 
Here is the repo I just prepared for this issue.
https://github.com/iAmBipinPaul/bullseye.issue.435

**Comment by adamralph** [comment] 2020-06-29 06:31
Thanks @iAmBipinPaul, I'll take a look ASAP.

**Comment by adamralph** [comment] 2020-06-29 08:26
@iAmBipinPaul as per the console output:

![image](https://user-images.githubusercontent.com/677704/85990569-84d50a80-b9f2-11ea-8e0a-eaac7f02a8f4.png)

If I run your example, and press Ctrl+C, the application shuts down, so it seems everything is fine.

Note that your `Worker` class is inheriting from `BackgroundService`, so I would expect this to run "in the background", rather than as part of a typical interactive console lifetime.

More generally though, I'm not sure `BackgroundService` is really suitable for running Bullseye targets. The lifetime of a typical Bullseye program is usually best represented by a simple console app. Is there a specific reason you are using `BackgroundService`?

**Comment by iAmBipinPaul** [comment] 2020-06-29 13:47
simple-exec
> If I run your example, and press Ctrl+C, the application shuts down, so it seems everything is fine.

Yes but if I I'm not pressing  Ctrl+C , while loops should be executing on interval of 1 second but it does not. It runs first time and then stops there , it should repeat the entire things which is inside the while loop.

```csharp
 protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            while (!stoppingToken.IsCancellationRequested)
            {
                Target("default", () => System.Console.WriteLine("Hello, world!"));
                RunTargetsWithoutExiting(default);
                _logger.LogInformation("Worker running at: {time}", DateTimeOffset.Now);
                await Task.Delay(1000, stoppingToken);
            }
        }
```

> More generally though, I'm not sure BackgroundService is really suitable for running Bullseye targets. The lifetime of a typical Bullseye program is usually best represented by a simple console app. Is there a specific reason you are using BackgroundService?

yes , I was looking for `simple-exec` and some how thought that `bullseye` is  `simple-exec`.

Thank you :) !

**Comment by adamralph** [comment] 2020-06-29 14:04
@iAmBipinPaul the problem is that this line, when executed a second time, throws an exception:

```c#
Target("default", () => System.Console.WriteLine("Hello, world!"));
```

This can be seen when setting VS to break when CLR exceptions are thrown:

![image](https://user-images.githubusercontent.com/677704/86015422-d648be00-ba21-11ea-960a-4475e27658b3.png)

I guess something in `Microsoft.Hosting.Extensions` is swallowing the exception.

Anyway, I believe we've determined that Bullseye is behaving as expected, so on that basis I'm closing the issue.

**Closed by adamralph** 2020-06-29 14:04 UTC
Labels: bug, invalid
